// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhzzdbiP4eBKHIkKd-ilDY8uz0XB5SR8',
    appId: '1:571138204622:web:48d7e03d813c637100419f',
    messagingSenderId: '571138204622',
    projectId: 'mobile-lab-flutter-firebase',
    authDomain: 'mobile-lab-flutter-firebase.firebaseapp.com',
    storageBucket: 'mobile-lab-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAMnP8m2NjdXMacpIotZevNKf7bXZd5Q',
    appId: '1:571138204622:android:ac5c469dc49a1c6c00419f',
    messagingSenderId: '571138204622',
    projectId: 'mobile-lab-flutter-firebase',
    storageBucket: 'mobile-lab-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwVR_sOtBq0duVwELxofa0FkapIxK_Io',
    appId: '1:571138204622:ios:3400ea15c0b8de8700419f',
    messagingSenderId: '571138204622',
    projectId: 'mobile-lab-flutter-firebase',
    storageBucket: 'mobile-lab-flutter-firebase.appspot.com',
    iosClientId: '571138204622-b90ijufsis629nom81t2naug38t1dpb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwVR_sOtBq0duVwELxofa0FkapIxK_Io',
    appId: '1:571138204622:ios:3400ea15c0b8de8700419f',
    messagingSenderId: '571138204622',
    projectId: 'mobile-lab-flutter-firebase',
    storageBucket: 'mobile-lab-flutter-firebase.appspot.com',
    iosClientId: '571138204622-b90ijufsis629nom81t2naug38t1dpb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );
}
